apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd-redis
  namespace: ctfd
  labels:
    app: ctfd-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctfd-redis
  template:
    metadata:
      labels:
        app: ctfd-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
