apiVersion: v1
kind: Service
metadata:
  name: ctfd
  namespace: ctfd
  labels:
    app: ctfd
spec:
  type: NodePort
  selector:
    app: ctfd
    component: web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ctfd-db
  namespace: ctfd
  labels:
    app: ctfd-db
spec:
  type: ClusterIP
  selector:
    app: ctfd-db
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: ctfd-redis
  namespace: ctfd
  labels:
    app: ctfd-redis
spec:
  type: ClusterIP
  selector:
    app: ctfd-redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
